from wtforms.fields import RadioField, SubmitField
from wtforms.form import Form
from wtforms.validators import DataRequired

class AssessmentForm(Form):
    choice_type_1 = [("Criteria Met", "Criteria Met"), ("Partial Compliance", "Partial Compliance"),("Criteria Not Met", "Criteria Not Met")]
    choice_type_2 = [("Yes", "Yes"), ("No", "No")]
    choice_type_3 = [("Always", "Always"), ("Almost", "Almost"), ("Never", "Never"), ("Almost Always", "Almost Always"), ("Sometimes", "Sometimes"), ("NA", "NA")]
    
    q_1 = RadioField(label="1.I have a chaperone present during sensitive examinations, regardless of patient gender. ", choices=choice_type_3, validators=[DataRequired()])
    q_2 = RadioField(label="2.The name of the chaperone is documented in the medical record. ", choices=choice_type_3, validators=[DataRequired()])
    q_3 = RadioField(label="3.Clinical practice guidelines are followed to provide evidence-based care.", choices=choice_type_3, validators=[DataRequired()])
    q_4 = RadioField(label="4.Vital signs (temperature, blood pressure, heart rate, and respiratory rate) are obtained and documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])      
    q_5 = RadioField(label="5.My practice follows a specific process to consistently notify patients of abnormal test results and documenting any recommended follow-up testing or treatment in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_6 = RadioField(label="6.I either speak with patients over the phone or they return to the office to discuss the abnormal results.", choices=choice_type_3, validators=[DataRequired()])
    # q_7 = RadioField(label="7.Patients can access their medical record and test results through a patient portal.", choices=choice_type_3, validators=[DataRequired()])
    # q_8 = RadioField(label="8.I stay current on age-appropriate malignancy screening and preventative health measures.", choices=choice_type_3, validators=[DataRequired()])
    # q_9 = RadioField(label="9.I participate in local continuing medical education courses.", choices=choice_type_3, validators=[DataRequired()])
    # q_10 = RadioField(label="10.I participate in national continuing medical education courses.", choices=choice_type_3, validators=[DataRequired()])
    # q_11 = RadioField(label="11.I read medical journals relevant to my practice.", choices=choice_type_3, validators=[DataRequired()])
    # q_12 = RadioField(label="12.I participate in CME courses and read articles provided, free of charge, by MagMutual.", choices=choice_type_3, validators=[DataRequired()])
    # q_13 = RadioField(label="13.A physician or advanced practice clinician conducts informed consent discussions with patients for all invasive procedures or treatments.", choices=choice_type_3, validators=[DataRequired()])
    # q_14 = RadioField(label="14.The informed consent discussion, including risks, benefits, alternatives and patient consent are documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_15 = RadioField(label="15.Informed consent forms are signed for invasive procedures and saved in the medical record. ", choices=choice_type_3, validators=[DataRequired()])
    # q_16 = RadioField(label="16.Patient non-compliance and/or informed refusal of care is documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_17 = RadioField(label="17.I reach out to The Institute's team of medical, legal and safety experts at MagMutual to assist me with patient safety, regulatory and operational questions.", choices=choice_type_3, validators=[DataRequired()])
    # q_18 = RadioField(label="18.Practice agreements and protocols, consistent with state laws and regulations, for advanced practice clinicians are followed, current and available.", choices=choice_type_3, validators=[DataRequired()])
    # q_19 = RadioField(label="19.Staff members performing procedures (e.g. injections, electrocardiograms) are qualified, trained and competencies are evaluated annually.", choices=choice_type_3, validators=[DataRequired()])
    # q_20 = RadioField(label="20.An internal peer review process is in place that includes provider-to-provider chart audits.", choices=choice_type_3, validators=[DataRequired()])
    # q_21 = RadioField(label="21.I participate in regular meetings within the organization to discuss quality initiatives, risk management and operations.", choices=choice_type_3, validators=[DataRequired()])
    # q_22 = RadioField(label="22.I review and countersign charts of advance practice clinicians I supervise within the same week of service.", choices=choice_type_3, validators=[DataRequired()])
    # q_23 = RadioField(label="23.I have input on whether a staff member is hired or fired at my place of work.", choices=choice_type_3, validators=[DataRequired()])
    # q_24 = RadioField(label="24.I participate in updating the operational policies and procedures of my organization.", choices=choice_type_3, validators=[DataRequired()])
    # q_25 = RadioField(label="25.I feel that I'm compensated appropriately for the job that I do. ", choices=choice_type_3, validators=[DataRequired()])
    # q_26 = RadioField(label="26.A current problem list and medical history is documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_27 = RadioField(label="27.Objective findings of the physical exam, including pertinent negatives, are documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_28 = RadioField(label="28.A physician or advanced practice clinician reviews all test results, signs and dates the result. For electronic health records, a electronic signature and date stamp is created. ", choices=choice_type_3, validators=[DataRequired()])
    # q_29 = RadioField(label="29.Treatment plans are consistent with working diagnosis and documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_30 = RadioField(label="30.How often do you utilize 'cloning', 'copying and pasting' and/or 'pulling forward' to document in the medical record .", choices=choice_type_3, validators=[DataRequired()])
    # q_31 = RadioField(label="31.A current list of medications is documented in the medical record, including over-the-counter and herbal supplements. The list includes medication dose and frequency.", choices=choice_type_3, validators=[DataRequired()])
    # q_32 = RadioField(label="32.The medication list is updated at each office visit and when medications are added/changed/discontinued.", choices=choice_type_3, validators=[DataRequired()])
    # q_33 = RadioField(label="33.Allergies and adverse drug reactions are documented and reviewed prior to prescribing.", choices=choice_type_3, validators=[DataRequired()])
    # q_34 = RadioField(label="34.Patients are informed of the serious side effects from medications with black box warnings.  ", choices=choice_type_3, validators=[DataRequired()])
    # q_35 = RadioField(label="35.Patients are instructed on new medications, especially high-risk medications that could pose a health risk if not taken appropriately and that instruction is documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_36 = RadioField(label="36.Patients prescribed new medications are monitored and asked about any side effects or concerns. Response to therapy is documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_37 = RadioField(label="37.A physician or advanced practice clinician authorizes all prescription refills or staff utilizes written protocols with provider sign off.", choices=choice_type_3, validators=[DataRequired()])
    # q_38 = RadioField(label="38.The EHR system has a built in alert system that prevents the prescriber from ordering medications that are documented in the system as an “allergy”.  ", choices=choice_type_3, validators=[DataRequired()])
    # q_39 = RadioField(label="39.The Physician is registered with the state prescription drug monitoring program and query the database according to state law.", choices=choice_type_3, validators=[DataRequired()])
    # q_40 = RadioField(label="40.Pain management plans of care are documented and reviewed with patients at each encounter.", choices=choice_type_3, validators=[DataRequired()])
    # q_41 = RadioField(label="41.If a patient is on high dose chronic opioid therapy, documentation in the chart reflects a plan to wean to a safe level or documentation reflects “why” the benefits of continued opioid therapy  outweighs the risks. ", choices=choice_type_3, validators=[DataRequired()])
    # q_42 = RadioField(label="42.My organization asks patients for feedback on their experience with an after visit survey.", choices=choice_type_3, validators=[DataRequired()])
    # q_43 = RadioField(label="43.My organization has a formal process to address patient complaints that includes notification and input from the physician involved in the patient's care.", choices=choice_type_3, validators=[DataRequired()])
    # q_44 = RadioField(label="44.I feel that my medical opinion and decision making ability is respected by my patients.", choices=choice_type_3, validators=[DataRequired()])
    # q_45 = RadioField(label="45.I have a wide variety of specialists within close geographic proximity that I can refer patients to with confidence.", choices=choice_type_3, validators=[DataRequired()])
    # q_46 = RadioField(label="46.I encounter barriers to specialty referral like geographical distance or insurance coverage.", choices=choice_type_3, validators=[DataRequired()])
    # q_47 = RadioField(label="47.I provide care via telemedicine.", choices=choice_type_3, validators=[DataRequired()])
    # q_48 = RadioField(label="48.There are challenges with telemedicine which prevent me from obtaining important information and not getting the whole clinical picture of the patient.", choices=choice_type_3, validators=[DataRequired()])
    # q_49 = RadioField(label="49.I'm aware of and stay updated on rules and regulations regarding telelmedine to ensure compliance.", choices=choice_type_3, validators=[DataRequired()])
    # q_50 = RadioField(label="50.After-hours calls and treatment advice is documented in the medical record. ", choices=choice_type_3, validators=[DataRequired()])
    # q_51 = RadioField(label="51.I review cross-coverage notes and advice given to my patients after hours.", choices=choice_type_3, validators=[DataRequired()])
    # q_52 = RadioField(label="52.Physician coverage for my organization is available 24 hours a day, 7 days a week.", choices=choice_type_3, validators=[DataRequired()])
    # q_53 = RadioField(label="53.A physician, advanced practice clinician or a licensed nurse answers all clinical questions and provides medical advice. ", choices=choice_type_3, validators=[DataRequired()])
    # q_54 = RadioField(label="54.Verbal and/or electronic communications with patients are documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])
    # q_55 = RadioField(label="55.I have enough time in my schedule to perform a medical chart review before I enter the room to see my patient.", choices=choice_type_3, validators=[DataRequired()])
    # q_56 = RadioField(label="56.I have enough time in my schedule to evaluate and examine the patient to my satisfaction.", choices=choice_type_3, validators=[DataRequired()])
    # q_57 = RadioField(label="57.I have enough time in my schedule to educate and counsel the patient at the end of the encounter.", choices=choice_type_3, validators=[DataRequired()])
    # q_58 = RadioField(label="58.My medical staff does the education and counseling part of the visit.", choices=choice_type_3, validators=[DataRequired()])
    # q_59 = RadioField(label="59.I routinely have enough time in my schedule to complete chart documentation the same day of service.", choices=choice_type_3, validators=[DataRequired()])
    # q_60 = RadioField(label="60.I routinely have enough time in my schedule to complete chart documentation within a week of service.", choices=choice_type_3, validators=[DataRequired()])
    # q_61 = RadioField(label="61.I have sufficient time or a cross-coverage system to connect my patients with a live provider during office off-hours to assist with their care and treatment.", choices=choice_type_3, validators=[DataRequired()])
    # q_62 = RadioField(label="62.Orders and referrals are tracked to ensure all results are received in a timely manner.", choices=choice_type_3, validators=[DataRequired()])
    # q_63 = RadioField(label="63.Reports are run and reviewed to check for outstanding orders/results on a routine basis", choices=choice_type_3, validators=[DataRequired()])
    # q_64 = RadioField(label="64.Patients with outstanding results or referrals are contacted to determine follow through with recommended testing/referral.", choices=choice_type_3, validators=[DataRequired()])       
    # q_65 = RadioField(label="65.If patients are contacted about outstanding results or referrals, that communication is documented in the medical record.", choices=choice_type_3, validators=[DataRequired()])



    qa_1 = RadioField(label="1.HIPAA training is provided for new employees and periodically thereafter.", choices=choice_type_1, validators=[DataRequired()])
    qa_2 = RadioField(label="2.The organization has performed a security risk assessment.", choices=choice_type_1, validators=[DataRequired()])
    qa_3 = RadioField(label="3.The organization has established EHR downtime procedures. ", choices=choice_type_1, validators=[DataRequired()])
    qa_4 = RadioField(label="4.Staff members involved in release of information receive training.", choices=choice_type_1, validators=[DataRequired()])
    qa_5 = RadioField(label="5.Safeguards are in place to protect the confidentiality, integrity, and availability of the ePHI on mobile devicesand in the cloud.", choices=choice_type_1, validators=[DataRequired()]) 
    # qa_6 = RadioField(label="6.The office has a policy that prohibits unauthorized audio/video recording.", choices=choice_type_1, validators=[DataRequired()])
    # qa_7 = RadioField(label="7.The practice has the capability of protecting the medical records of patients who are employees of the practice.", choices=choice_type_1, validators=[DataRequired()])
    # qa_8 = RadioField(label="8.The practice has a social media policy.", choices=choice_type_1, validators=[DataRequired()])
    # qa_9 = RadioField(label="9.There is a formalized policy for handling HIPAA-related complaints.", choices=choice_type_1, validators=[DataRequired()])
    # qa_10 = RadioField(label="10.The practice has an established written process to guide the user in making amendments within the medical record.", choices=choice_type_1, validators=[DataRequired()])
    # qa_11 = RadioField(label="11.The organization has HIPAA policies and procedures in place.", choices=choice_type_1, validators=[DataRequired()])
    # qa_12 = RadioField(label="12.The organization has a mobile device policy.", choices=choice_type_1, validators=[DataRequired()])
    # qa_13 = RadioField(label="13.The practice posts in a prominent location a notice of non-discrimination on the basis of race, color, national origin, sex, age, or disability in its health programs and activities.", choices=choice_type_1, validators=[DataRequired()])
    # qa_14 = RadioField(label="14.The notice provides information on how to file a grievance (for 15+ employees).", choices=choice_type_1, validators=[DataRequired()])
    # qa_15 = RadioField(label="15.The notice provides information on how to file a complaint with the Office of Civil Rights.", choices=choice_type_1, validators=[DataRequired()])
    # qa_16 = RadioField(label="16.The practice provides free aids and services to people with disabilities, including qualified sign language interpreters and written information in other formats.", choices=choice_type_1, validators=[DataRequired()])
    # qa_17 = RadioField(label="17.The practice provides free language assistance services to people whose primary language is not English, including qualified interpreters and information written in other languages.", choices=choice_type_1, validators=[DataRequired()])
    # qa_18 = RadioField(label="18.The practice provides “taglines” in at least the top 15 languages spoken by people with limited English proficiency in the relevant state.", choices=choice_type_1, validators=[DataRequired()])
    # qa_19 = RadioField(label="19.Programs or activities which are provided through electronic means are accessible to individuals with disabilities, unless doing so would result in an undue financial burden or fundamentally alter the nature of the program or activity", choices=choice_type_1, validators=[DataRequired()])
    # qa_20 = RadioField(label="20.The practice maintains a written exposure control plan that is updated annually.", choices=choice_type_1, validators=[DataRequired()])
    # qa_21 = RadioField(label="21.Appropriate personal protective equipment (gloves, face/eye protection, gowns) is available.", choices=choice_type_1, validators=[DataRequired()])
    # qa_22 = RadioField(label="22.There is a policy for an exposure incident.", choices=choice_type_1, validators=[DataRequired()])
    # qa_23 = RadioField(label="23.The practice uses labels or color-coding for items such as sharps disposal boxes and containers for regulated waste, contaminated laundry, and certain specimens.", choices=choice_type_1, validators=[DataRequired()])
    # qa_24 = RadioField(label="24.Employees for whom contact with blood or other potentially infectious material is anticipated are trained on the OSHA bloodborne pathogens standard upon hire and at least annually. ", choices=choice_type_1, validators=[DataRequired()])
    # qa_25 = RadioField(label="25.The practice maintains a written hazard communication plan (29 CFR 1910.1200).", choices=choice_type_1, validators=[DataRequired()])
    # qa_26 = RadioField(label="26.The practice maintains a current list of hazardous chemicals (such as alcohol, disinfectants, anesthetic agents, sterilants) used or stored in the office.", choices=choice_type_1, validators=[DataRequired()])
    # qa_27 = RadioField(label="27.The practice maintains Safety Data Sheets for each chemical used or stored in the office.", choices=choice_type_1, validators=[DataRequired()])
    # qa_28 = RadioField(label="28.The practice has conducted a workplace violence hazard analysis and has a workplace violence prevention plan.", choices=choice_type_1, validators=[DataRequired()])
    # qa_29 = RadioField(label="29.Fire evacuation routes are posted within the practice.", choices=choice_type_1, validators=[DataRequired()])
    # qa_30 = RadioField(label="30.The practice maintains ADA-compliant job descriptions for all positions.", choices=choice_type_1, validators=[DataRequired()])
    # qa_31 = RadioField(label="31.There is an orientation process for all new staff members.", choices=choice_type_1, validators=[DataRequired()])
    # qa_32 = RadioField(label="32.Practice agreements (as required by state law) are on file for advanced practice clinicians.", choices=choice_type_1, validators=[DataRequired()])
    # qa_33 = RadioField(label="33.Staff members do not perform tasks beyond their scope of licensure, certification or training.", choices=choice_type_1, validators=[DataRequired()])
    # qa_34 = RadioField(label="34.There is a formal credentialing and periodic re-credentialing process for all providers (e.g. physicians or other licensed independent or dependent practitioners) associated with the office practice.", choices=choice_type_1, validators=[DataRequired()])
    # qa_35 = RadioField(label="35.There is a mechanism for periodically reassessing each employee’s competence.", choices=choice_type_1, validators=[DataRequired()])
    # qa_36 = RadioField(label="36.The practice has an anti-harassment policy and provides periodic training.", choices=choice_type_1, validators=[DataRequired()])
    # qa_37 = RadioField(label="37.Practice staff are familiar with minor consent laws.", choices=choice_type_1, validators=[DataRequired()])
    # qa_38 = RadioField(label="38.There are procedures for handling a minor who presents for treatment who is unaccompanied by a parent or guardian.", choices=choice_type_1, validators=[DataRequired()])
    # qa_39 = RadioField(label="39.A current list of medications is documented in the medical record, including over-the-counter and herbal supplements. The list includes medication dose and frequency", choices=choice_type_1, validators=[DataRequired()])
    # qa_40 = RadioField(label="40.The medication list is updated at each office visit and when medications are added/changed/discontinued.", choices=choice_type_1, validators=[DataRequired()])
    # qa_41 = RadioField(label="41.Allergies are listed and displayed prominently; updated as necessary.", choices=choice_type_1, validators=[DataRequired()])
    # qa_42 = RadioField(label="42.Immunization status is documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_43 = RadioField(label="43.Medications are prepared in a clean area.", choices=choice_type_1, validators=[DataRequired()])
    # qa_44 = RadioField(label="44.Vaccine administration is documented including date, dose, expiration date, manufacturer and lot number.", choices=choice_type_1, validators=[DataRequired()])
    # qa_45 = RadioField(label="45.Vaccines are either entered into vaccine log or, if electronically documented, history of same may be accessed electronically.", choices=choice_type_1, validators=[DataRequired()])   
    # qa_46 = RadioField(label="46.Parents/guardians and patients are educated about the benefits and risks of vaccination in a culturally appropriate manner and in an easy-to-understand language", choices=choice_type_1, validators=[DataRequired()])
    # qa_47 = RadioField(label="47.If samples are maintained in the office:", choices=choice_type_1, validators=[DataRequired()])
    # qa_48 = RadioField(label="48.There is a drug sample control program that includes inventory, monthly checks of expiration dates and a recall system.", choices=choice_type_1, validators=[DataRequired()])
    # qa_49 = RadioField(label="49.Sample tracking logs are utilized when samples are dispensed.", choices=choice_type_1, validators=[DataRequired()])
    # qa_50 = RadioField(label="50.Samples are dispensed directly by the physician, or, if dispensed by the MA, correct patient, drug, dose, route and frequency are verified by the physician prior to handing to patient.  ", choices=choice_type_1, validators=[DataRequired()])
    # qa_51 = RadioField(label="51.Sample closet is secured to prevent diversion of medication.", choices=choice_type_1, validators=[DataRequired()])
    # qa_52 = RadioField(label="52.Medication refrigerator temps are checked at least daily; if out of range temps are documented, appropriate corrective action is undertaken, documented and follow-up temp is completed.", choices=choice_type_1, validators=[DataRequired()])
    # qa_53 = RadioField(label="53.There is a monitoring process in place so that if the temperature of the medicationrefrigerator went out of range during off-hours, the staff would be aware of it upon return to the office.", choices=choice_type_1, validators=[DataRequired()])
    # qa_54 = RadioField(label="54.Medications are stored in refrigerators, separate from chemicals, oral contrast, lab reagents, food, etc.", choices=choice_type_1, validators=[DataRequired()])
    # qa_55 = RadioField(label="55.Stocked medication,including biological and samples, prescription pads,and syringes are stored in a secure area; inventoried, and controlled.", choices=choice_type_1, validators=[DataRequired()])
    # qa_56 = RadioField(label="56.Processesfor administering medications includes proper patient identification and order verification before administration.", choices=choice_type_1, validators=[DataRequired()])      
    # qa_57 = RadioField(label="57.Single dose vials are used for one patient only and discarded after one use. (CDC guidelines on Safe Injection practices are followed.)", choices=choice_type_1, validators=[DataRequired()])
    # qa_58 = RadioField(label="58.Multi-dose vials are dated with a 28-day expiration date, unless manufacturer’s expiration date precedes that date.", choices=choice_type_1, validators=[DataRequired()])
    # qa_59 = RadioField(label="59.Medications from multi-dose vials are drawn up with a clean needle and syringe each time the stopper is pierced.  (If the same needle or the same syringe is used, the vial is considered to be single patient use and is discarded after the patient leaves.)", choices=choice_type_1, validators=[DataRequired()])
    # qa_60 = RadioField(label="60.Medications drawn up from a multi-dose vial in a non-patient care area are labeled with the drug name, dose, and concentration unless administered immediately.", choices=choice_type_1, validators=[DataRequired()])
    # qa_61 = RadioField(label="61.Providers review every prescription refillrequest.", choices=choice_type_1, validators=[DataRequired()])
    # qa_62 = RadioField(label="62.A copy of all medication orders and prescriptions are maintained in the patient’s medicalrecord.", choices=choice_type_3, validators=[DataRequired()])
    # qa_63 = RadioField(label="63.All medications dispensed from the office are properly labeled.", choices=choice_type_1, validators=[DataRequired()])
    # qa_64 = RadioField(label="64.Policies prohibit the use of pre-signed and /or postdated prescription forms.", choices=choice_type_1, validators=[DataRequired()])
    # qa_65 = RadioField(label="65.There are protocols for handling patient requests for prescription renewals.", choices=choice_type_1, validators=[DataRequired()])
    # qa_66 = RadioField(label="66.There is a policy that requires a “read back” of the complete order by the person taking verbal or telephone medication orders.", choices=choice_type_1, validators=[DataRequired()])  
    # qa_67 = RadioField(label="67.Two patient identifiers are confirmed and drug orders verified before administration of medications.", choices=choice_type_1, validators=[DataRequired()])
    # qa_68 = RadioField(label="68.There is a process for handling drug recalls.", choices=choice_type_1, validators=[DataRequired()])
    # qa_69 = RadioField(label="69.The emergency kit is checked periodically for expired drugs/supplies.", choices=choice_type_1, validators=[DataRequired()])
    # qa_70 = RadioField(label="70.Medications prepared in distraction-free zone", choices=choice_type_1, validators=[DataRequired()])
    # qa_71 = RadioField(label="71.Providers are registered for state PDMP and query according to state laws/regulations.", choices=choice_type_1, validators=[DataRequired()])
    # qa_72 = RadioField(label="72.There is an informed consent process for long-term, non-malignant opioid therapy which includes a written agreement", choices=choice_type_3, validators=[DataRequired()])
    # qa_73 = RadioField(label="73.Patients can request a chaperone for any examination.", choices=choice_type_1, validators=[DataRequired()])
    # qa_74 = RadioField(label="74.A patient’s request for a chaperone is honored.", choices=choice_type_1, validators=[DataRequired()])
    # qa_75 = RadioField(label="75.A chaperone is used for intimate exams even when a trusted companion is present.", choices=choice_type_1, validators=[DataRequired()])
    # qa_76 = RadioField(label="76.The exam of an infant, toddler, or childis always performed in the presence of a parent or guardian.", choices=choice_type_1, validators=[DataRequired()])
    # qa_77 = RadioField(label="77.The presence of a chaperone and their identity (name and full job title rather than a generic phrase such as 'duty nurse') is documented in the medical record.", choices=choice_type_1, validators=[DataRequired()])
    # qa_78 = RadioField(label="78.There is a written emergency protocol that outlines the steps to be followed in the event of an emergency.", choices=choice_type_1, validators=[DataRequired()])
    # qa_79 = RadioField(label="79.The choice of emergency medications and equipment reflects the spectrum of anticipated emergencies in a practice’s patient population, the skills of the practitioners, and the distance to the nearest emergency department.", choices=choice_type_1, validators=[DataRequired()])
    # qa_80 = RadioField(label="80.Emergency bundles/kits are maintained for the most likely emergencies.", choices=choice_type_1, validators=[DataRequired()])
    # qa_81 = RadioField(label="81.Office providers and staff maintain current certification in basic or advanced life support.", choices=choice_type_1, validators=[DataRequired()])
    # qa_82 = RadioField(label="82.Informed consent is obtained and documented for all invasive procedures or treatments with more than a minimal amount of risk and as required by law.", choices=choice_type_1, validators=[DataRequired()])
    # qa_83 = RadioField(label="83.Informed consent discussions are documented in the medical record by the provider.", choices=choice_type_1, validators=[DataRequired()])
    # qa_84 = RadioField(label="84.Patient consent is obtained and documented for the taking of photographs, videotapes, or other identifiable images of a patient.", choices=choice_type_3, validators=[DataRequired()]) 
    # qa_85 = RadioField(label="85.Consent formscontain the signature of the patient or his/her legal representative, thedate and time of the signature, and the signature of the provider who conducted the informed consent discussion.", choices=choice_type_1, validators=[DataRequired()])
    # qa_86 = RadioField(label="86.The patient is notified in writing by registered or certified mail of dismissal fromthe practice.", choices=choice_type_1, validators=[DataRequired()])
    # qa_87 = RadioField(label="87.The termination letter informsthe patient about how to obtain the services of another physician and clearly statesthe effective termination date.", choices=choice_type_1, validators=[DataRequired()])
    # qa_88 = RadioField(label="88.When terminating the patient-physician relationship, the patient or authorized decision maker is notified long enough in advance to permit the patient to secure another physician.", choices=choice_type_1, validators=[DataRequired()])
    # qa_89 = RadioField(label="89.Medical records are made available to the new physician upon receipt of the patient's authorization.", choices=choice_type_1, validators=[DataRequired()])
    # qa_90 = RadioField(label="90.The practice has a pre-procedure verification process that meets the universal protocol for preventing wrong procedure, wrong site, and wrong person surgery. ", choices=choice_type_1, validators=[DataRequired()])
    # qa_91 = RadioField(label="91.Patients are assessed and monitored before, during, and after officeprocedures according to medical need andapplicablestandards of practice.", choices=choice_type_1, validators=[DataRequired()])
    # qa_92 = RadioField(label="92.The use of sedation or any other non-local anesthesia is governed by policies and procedures addressing provider/ staff competency, patient eligibility, informed consent, clinical monitoring, and emergency interventions.", choices=choice_type_1, validators=[DataRequired()])
    # qa_93 = RadioField(label="93.Containers used for blood and other specimens are labeled in the presence of the patient.", choices=choice_type_1, validators=[DataRequired()])
    # qa_94 = RadioField(label="94.The practice has a system for early detection and management of potentially infectious persons at initial points of patient encounter. ", choices=choice_type_1, validators=[DataRequired()])
    # qa_95 = RadioField(label="95.The practice complies with mandatory reporting requirements for notifiable diseases, healthcare associated infections (as appropriate), and for potential outbreaks.", choices=choice_type_1, validators=[DataRequired()])
    # qa_96 = RadioField(label="96.Patients who have undergone procedures in the office are educated regarding the signs and symptoms of infectionthat may be associated with the procedure and instructed to notify the provider if such signs or symptoms occur.", choices=choice_type_1, validators=[DataRequired()])
    # qa_97 = RadioField(label="97.Employees demonstrate competency with hand hygiene.", choices=choice_type_1, validators=[DataRequired()])
    # qa_98 = RadioField(label="98.Hand hygiene policies promote preferential use of alcohol-based hand rub over soap and water in most clinical situations ", choices=choice_type_1, validators=[DataRequired()])        
    # qa_99 = RadioField(label="99.Clinical staff are required to demonstrate competency with safe injection practices following each training.", choices=choice_type_1, validators=[DataRequired()])
    # qa_100 = RadioField(label="100.The practice has policies and procedures to contain respiratory secretions in persons who have signs and symptoms of a respiratory infection, beginning at point of entry to the facility and continuing through the duration of the visit.", choices=choice_type_1, validators=[DataRequired()])
    # qa_101 = RadioField(label="101.Clinical staff who perform point-of-care testing receive training on recommended practices.", choices=choice_type_1, validators=[DataRequired()])
    # qa_102 = RadioField(label="102.Facility has written policies and procedures for routine cleaning and disinfection of environmental surfaces, including identification of responsible personnel", choices=choice_type_1, validators=[DataRequired()])
    # qa_103 = RadioField(label="103.Appointments that are missed, rescheduled, or cancelled by the patient or providerare documented in the medical record.", choices=choice_type_1, validators=[DataRequired()])        
    # qa_104 = RadioField(label="104.Test results are tracked, reconciled and acted upon in a timely manner prior to filing/releasingin the medical record.", choices=choice_type_1, validators=[DataRequired()])
    # qa_105 = RadioField(label="105.There is a standardized system for reviewing/signing incoming reports and correspondence.", choices=choice_type_1, validators=[DataRequired()])
    # qa_106 = RadioField(label="106.Referrals are facilitated by the practice and documented in the medical record.", choices=choice_type_1, validators=[DataRequired()])
    # qa_107 = RadioField(label="107.The reason and urgency for the referral is communicated and an appointment is made before the patient leaves the office.", choices=choice_type_1, validators=[DataRequired()])       
    # qa_108 = RadioField(label="108.There is a procedure to identify outstanding reports from consultants.", choices=choice_type_1, validators=[DataRequired()])
    # qa_109 = RadioField(label="109.Providers review and acknowledge receipt of all incoming consultant reports.", choices=choice_type_1, validators=[DataRequired()])
    # qa_110 = RadioField(label="110.Patients are notified of testresults.", choices=choice_type_1, validators=[DataRequired()])
    # qa_111 = RadioField(label="111.Patients are informed ofwhen test results are expected and asked to call for results if not contacted by the expected date. ", choices=choice_type_1, validators=[DataRequired()])   
    # qa_112 = RadioField(label="112.There is a mechanism for reporting urgent information to the provider immediately.", choices=choice_type_1, validators=[DataRequired()])
    # qa_113 = RadioField(label="113.Providersand staff are trained in the use of office equipment during orientation and on all new devices before they areplaced into use.", choices=choice_type_1, validators=[DataRequired()])
    # qa_114 = RadioField(label="114.All equipment is periodically inspected, tested, and preventive maintenance performed.", choices=choice_type_1, validators=[DataRequired()])
    # qa_115 = RadioField(label="115.Inspection and preventive maintenance procedures are documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_116 = RadioField(label="116.Medical records are readily available to providers when needed (e.g., when treating patients in the office or over the telephone).", choices=choice_type_1, validators=[DataRequired()])
    # qa_117 = RadioField(label="117.Drug, food, and other allergy information is documented prominently in the medical record.", choices=choice_type_1, validators=[DataRequired()])
    # qa_118 = RadioField(label="118.All medical record entries are signed and dated.", choices=choice_type_1, validators=[DataRequired()])
    # qa_119 = RadioField(label="119.Patient education regarding health problems, medications, and plan of care is documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_120 = RadioField(label="120.Patients receive written instructions and information regarding self-care and follow-up recommendations.", choices=choice_type_1, validators=[DataRequired()])
    # qa_121 = RadioField(label="121.Patient noncompliance and/or declination of recommended treatment is documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_122 = RadioField(label="122.Telephone/text messages in which a provider or staff member provides orders or treatment advice is documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_123 = RadioField(label="123.If off-site storage is used for electronic records, backup systems are in place.", choices=choice_type_1, validators=[DataRequired()])
    # qa_124 = RadioField(label="124.Applicable medical record retention requirements are considered when thinning medicalrecords.", choices=choice_type_1, validators=[DataRequired()])
    # qa_125 = RadioField(label="125.The practice has adopted a standardized list of abbreviations, acronyms, and symbols to use and not to use.", choices=choice_type_1, validators=[DataRequired()])
    # qa_126 = RadioField(label="126.The practice has a medical record completion policy and monitors compliance.", choices=choice_type_1, validators=[DataRequired()])
    # qa_127 = RadioField(label="127.Disclaimers regarding the accuracy oftranscribed documentation are not used", choices=choice_type_3, validators=[DataRequired()])
    # qa_128 = RadioField(label="128.The practice has an event reporting system.", choices=choice_type_1, validators=[DataRequired()])
    # qa_129 = RadioField(label="129.Employees are encouraged to report unanticipated events/errors.", choices=choice_type_1, validators=[DataRequired()])
    # qa_130 = RadioField(label="130.Incident reports are not included in the medical record.", choices=choice_type_1, validators=[DataRequired()])
    # qa_131 = RadioField(label="131.Potentially compensable events are reported to the insurance carrier in a timely manner.", choices=choice_type_1, validators=[DataRequired()])
    # qa_132 = RadioField(label="132.There is a policy for investigating slips, trips, falls, and other employee/visitor incidents.", choices=choice_type_1, validators=[DataRequired()])
    # qa_133 = RadioField(label="133.If the practice maintains a website, content is reviewed for false claims in advertising", choices=choice_type_1, validators=[DataRequired()])
    # qa_134 = RadioField(label="134.Consistent patient information and evidence of privacy notice provided available.", choices=choice_type_1, validators=[DataRequired()])
    # qa_135 = RadioField(label="135.Allergies and adverse drug reactions are documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_136 = RadioField(label="136.There is a current problem list and medical history.", choices=choice_type_1, validators=[DataRequired()])
    # qa_137 = RadioField(label="137.There is current list of medications, known prescriptions, over-the-counter medication, herbals, and vitamins/supplements including the dose, route, frequency, and purpose.", choices=choice_type_1, validators=[DataRequired()])
    # qa_138 = RadioField(label="138.Family history, including history of cancer, is documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_139 = RadioField(label="139.Significant telephone encounters are documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_140 = RadioField(label="140.Vital signs are documented for post-op patients or patients with an acute illness.", choices=choice_type_1, validators=[DataRequired()])
    # qa_141 = RadioField(label="141.Objective findings of the physical exam are documented.", choices=choice_type_1, validators=[DataRequired()])
    # qa_142 = RadioField(label="142.Documentation that a chaperone was present or refused.", choices=choice_type_1, validators=[DataRequired()])
    # qa_143 = RadioField(label="143.Assessment/working diagnosis consistent with subjective/objective findings", choices=choice_type_1, validators=[DataRequired()])
    # qa_144 = RadioField(label="144.Treatment plan or plan of action is present.", choices=choice_type_1, validators=[DataRequired()])
    # qa_145 = RadioField(label="145.Plan of action (treatment plan) is consistent with working diagnosis.", choices=choice_type_1, validators=[DataRequired()])
    # qa_146 = RadioField(label="146.Informed consent discussions and form documented for invasive procedures.", choices=choice_type_1, validators=[DataRequired()])
    # qa_147 = RadioField(label="147.Written post-procedure instructions are provided to patients.", choices=choice_type_1, validators=[DataRequired()])
    # qa_148 = RadioField(label="148.Medications administered have dose, route, and site documented. For vaccines, additional documentation includes manufacturer, lot number, and VIS (vaccine information statement).", choices=choice_type_1, validators=[DataRequired()])
    # qa_149 = RadioField(label="149.Evidence that test/lab results viewed by a provider and findings communicated to patient.", choices=choice_type_1, validators=[DataRequired()])
    
    submit = SubmitField(label ="Submit")